/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Board */
        get: operations["board_api_board_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Budget Route */
        get: operations["budget_route_api_budget_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/failures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Failures */
        get: operations["failures_api_failures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pending-intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pending Intents */
        get: operations["pending_intents_api_pending_intents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Queue View */
        get: operations["queue_view_api_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/boost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue Boost */
        post: operations["queue_boost_api_queue_boost_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue Next */
        post: operations["queue_next_api_queue_next_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue Ready */
        post: operations["queue_ready_api_queue_ready_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task/{issue}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Detail */
        get: operations["task_detail_api_task__issue__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task/{issue}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task History */
        get: operations["task_history_api_task__issue__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task/{issue}/kill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Intent Kill */
        post: operations["intent_kill_api_task__issue__kill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task/{issue}/park": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Intent Park */
        post: operations["intent_park_api_task__issue__park_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task/{issue}/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Intent Reply */
        post: operations["intent_reply_api_task__issue__reply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task/{issue}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Intent Resume */
        post: operations["intent_resume_api_task__issue__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task/{issue}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Intent Retry */
        post: operations["intent_retry_api_task__issue__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task/{issue}/spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Spec */
        get: operations["task_spec_api_task__issue__spec_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BoardView */
        BoardView: {
            capacity: components["schemas"]["CapacityView"];
            /** Columns */
            columns: components["schemas"]["Column"][];
        };
        /** BoostReq */
        BoostReq: {
            /** Amount */
            amount: number;
            /** Issue */
            issue: number;
        };
        /** BudgetView */
        BudgetView: {
            /** Minutes To Reset */
            minutes_to_reset: number;
            /** Source */
            source: string;
            /** Threshold Applied */
            threshold_applied: string;
            /** Utilization */
            utilization: number;
            /** Would Spawn */
            would_spawn: boolean;
        };
        /** CapacityView */
        CapacityView: {
            /** Active */
            active: number;
            /** Capacity */
            capacity: number;
            /** Max Slots */
            max_slots: number;
            /** Slots Used */
            slots_used: number;
        };
        /** Column */
        Column: {
            /** Cards */
            cards: components["schemas"]["TaskCard"][];
            /** Key */
            key: string;
            /** Title */
            title: string;
        };
        /** EventEntry */
        EventEntry: {
            /** Actor */
            actor: string;
            /** Detail */
            detail: string;
            /** Event */
            event: string;
            /** Issue */
            issue: number;
            /** Model */
            model: string;
            /** Stage */
            stage: string;
            /** Target */
            target: string;
            /** Ts */
            ts: string;
        };
        /** FailuresView */
        FailuresView: {
            /** Fingerprints */
            fingerprints: components["schemas"]["FingerprintEntry"][];
            /** Quarantined */
            quarantined: components["schemas"]["QuarantineEntry"][];
        };
        /** FingerprintEntry */
        FingerprintEntry: {
            /** Fingerprint */
            fingerprint: string;
            /** Issue */
            issue: number;
            /** Repo */
            repo: string;
            /** When */
            when: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryView */
        HistoryView: {
            /** Events */
            events: components["schemas"]["EventEntry"][];
        };
        /** NextReq */
        NextReq: {
            /**
             * Force
             * @default false
             */
            force: boolean;
            /** Issue */
            issue: number;
        };
        /** PaneHistory */
        PaneHistory: {
            /** Text */
            text: string;
        };
        /** QuarantineEntry */
        QuarantineEntry: {
            /** Blocker Issue */
            blocker_issue: number;
            /** Blocker Open */
            blocker_open: boolean | null;
            /** Blocker Repo */
            blocker_repo: string;
            /** Created At */
            created_at: string;
            /** Fingerprint */
            fingerprint: string;
            /** Target */
            target: string;
            /** Task Issue */
            task_issue: number;
        };
        /** QueueRow */
        QueueRow: {
            /** Blocked */
            blocked: boolean;
            /** Boost */
            boost: number;
            /** In Flight */
            in_flight: boolean;
            /** Labels */
            labels: string[];
            /** Number */
            number: number;
            /** Score */
            score: number | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** QueueView */
        QueueView: {
            /** Targets */
            targets: components["schemas"]["TargetQueue"][];
        };
        /** ReadyReq */
        ReadyReq: {
            /** Issue */
            issue: number;
        };
        /** ReplyReq */
        ReplyReq: {
            /** Text */
            text: string;
        };
        /** ResumeReq */
        ResumeReq: {
            /**
             * Text
             * @default
             */
            text: string;
        };
        /** SpecView */
        SpecView: {
            /** Markdown */
            markdown: string;
            /** Path */
            path: string;
        };
        /** TargetQueue */
        TargetQueue: {
            /** As Of */
            as_of: string;
            /** Rows */
            rows: components["schemas"]["QueueRow"][];
            /** Stale */
            stale: boolean;
            /** Target */
            target: string;
        };
        /** TaskCard */
        TaskCard: {
            /** Attached */
            attached: boolean;
            /** Branch */
            branch: string;
            /** Column */
            column: string;
            /** Issue */
            issue: number;
            /** Model */
            model: string;
            /** Park */
            park: string;
            /** Park Note Pending */
            park_note_pending: boolean;
            /** Slot */
            slot: number;
            /** Stage */
            stage: string;
            /** Target */
            target: string;
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string;
        };
        /** TaskDetail */
        TaskDetail: {
            card: components["schemas"]["TaskCard"];
            /** Ci Run Id */
            ci_run_id: number;
            /** Effort */
            effort: number | null;
            /** Labels */
            labels: string[];
            /** Pane Tail */
            pane_tail: string;
            /** Pending Reply */
            pending_reply: string;
            /** Session Alive */
            session_alive: boolean;
            /** Worktree */
            worktree: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    board_api_board_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardView"];
                };
            };
        };
    };
    budget_route_api_budget_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetView"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    failures_api_failures_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FailuresView"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    history_api_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pending_intents_api_pending_intents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    queue_view_api_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueView"];
                };
            };
        };
    };
    queue_boost_api_queue_boost_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoostReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_next_api_queue_next_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NextReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_ready_api_queue_ready_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReadyReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_detail_api_task__issue__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issue: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_history_api_task__issue__history_get: {
        parameters: {
            query?: {
                lines?: number;
            };
            header?: never;
            path: {
                issue: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaneHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    intent_kill_api_task__issue__kill_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issue: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    intent_park_api_task__issue__park_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issue: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    intent_reply_api_task__issue__reply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issue: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplyReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    intent_resume_api_task__issue__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issue: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    intent_retry_api_task__issue__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issue: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_spec_api_task__issue__spec_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issue: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
